version: '3.8'

services:
  frontend:
    build: ./frontend
    container_name: frontend_project
    ports:
      - "4173:4173"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build: ./backend
    container_name: backend_project
    ports:
      - "4000:4000"
    volumes:
      - ./backend/src:/app/src        
      - ./backend/tsconfig.json:/app/tsconfig.json
      - ./backend/.env:/app/.env
    depends_on:
      - dbpostgre
    environment:
      - DATABASE_URL=${DATABASE_URL}
    networks:
      - app-network

  dbpostgre:
    image: postgres:16
    container_name: portfolio_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
