# Use Node 22
FROM node:22

# Define diretório de trabalho
WORKDIR /app

# Copia arquivos de dependências e instala
COPY package*.json ./
COPY prisma ./prisma
RUN npm install

# Copia o restante do código
COPY . .

# Gera o Prisma Client
RUN npx prisma generate

# Comando para rodar em dev (com watch)
CMD ["npm", "run", "dev"]
